# Generated by Django 3.1.7 on 2021-05-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',)},
        ),
    ]
