# Generated by Django 3.1.7 on 2021-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='json',
            field=models.JSONField(null=True),
        ),
    ]
