# Generated by Django 3.1.7 on 2021-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210515_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='user',
            field=models.CharField(default='', max_length=30, null=True, unique=True),
        ),
    ]
